jobs:

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  variables:
    PROFILE: 'profiles/windows_x86_64_visual_studio_15_2017'
  timeoutInMinutes: 0
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
  - template: templates/setup-conan.yml
  - script: |
      conan create -pr $(PROFILE) -r kwc_bintray -b outdated -s build_type=$(BUILD_TYPE) asio kwc_bintray/stable
      conan upload -r kwc_bintray --all --confirm asio

      conan create -pr $(PROFILE) -r kwc_bintray -b outdated -s build_type=$(BUILD_TYPE) hdf5 kwc_bintray/stable
      conan upload -r kwc_bintray --all --confirm hdf5

      conan create -pr $(PROFILE) -r kwc_bintray -b outdated -s build_type=$(BUILD_TYPE) Qt kwc_bintray/stable
      conan upload -r kwc_bintray --all --confirm Qt

      conan create -pr $(PROFILE) -r kwc_bintray -b outdated -s build_type=$(BUILD_TYPE) simpleini kwc_bintray/stable
      conan upload -r kwc_bintray --all --confirm simpleini

      conan create -pr $(PROFILE) -r kwc_bintray -b outdated -s build_type=$(BUILD_TYPE) spdlog kwc_bintray/stable
      conan upload -r kwc_bintray --all --confirm spdlog

      conan create -pr $(PROFILE) -r kwc_bintray -b outdated -s build_type=$(BUILD_TYPE) tclap kwc_bintray/stable
      conan upload -r kwc_bintray --all --confirm tclap
  strategy:
    matrix:
      Release:
        BUILD_TYPE: 'Release'

