jobs:

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  variables:
    PROFILE: 'profiles/windows_x86_64_visual_studio_15_2017'
  timeoutInMinutes: 0
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
  - template: templates/setup-conan.yml
  - script: |
      conan create -pr $(PROFILE) -r kwc_bintray -b outdated -s build_type=$(BUILD_TYPE) tclap kwc_bintray/stable
  strategy:
    matrix:
      Release:
        BUILD_TYPE: 'Release'

